name: Ubuntu-kvm
on:
  create:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check our path
        run: pwd
      # $GITHUB_WORKSPACE/qemu_github 
      - name: Installing qemu via apt
        run: sudo apt install qemu qemu-system-misc *kvm* -y
      - name: Checking whether qemu-kvm is available
        run: qemu-kvm --version
      - name: Investigating which machine types qemu-kvm supports
        run: qemu-kvm -M help
      - name: Investigating which CPU arch. are supported by qemu-kvm
        run: qemu-kvm -cpu help
