name: Ubuntu-kvm
on:
  create:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check our path
        run: pwd
      # $GITHUB_WORKSPACE/qemu_github 
      - name: Installing qemu via apt
        run: sudo apt-get update -y && sudo apt install qemu qemu-system-misc qemu-kvm -y
      - name: Checking whether qemu-kvm is available
        run: kvm --version
      - name: Investigating which machine types qemu-kvm supports
        run: kvm -M help
      - name: Investigating which CPU arch. are supported by qemu-kvm
        run: kvm -cpu help
      - name: Requesting CPU features
        run: egrep -c '(vmx|svm)' /proc/cpuinfo
      - name: Validating KVM's infrastructure
        run: sudo kvm-ok
