name: Fedora
on:
  create:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check our path
        run: pwd
      # $GITHUB_WORKSPACE/qemu_github 
      - name: Installing qemu via apt
        run: sudo apt install qemu qemu-system-misc -y
      - name: Checking whether qemu is available 
        run: qemu-system-riscv64 --version
      - name: Checking if virtio* flags are supported
        run:  qemu-system-riscv64 -nographic -machine virt -smp 8 -m 2G -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-device,rng=rng0  -device virtio-blk-device,drive=hd0  -drive file=Fedora-Developer-Rawhide-*.raw,format=raw,id=hd0 -device virtio-net-device,netdev=usernet  -netdev user,id=usernet,hostfwd=tcp::10000-:22
