name: Fedora
on:
  create:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check our path
        run: pwd
      # $GITHUB_WORKSPACE/qemu_github 
      - name: List free vRAM and check swap
        run: free -h && swapon -a
      - name: Mounting tmpfs
        run: mkdir /tmp/qemu_storage && sudo mount -t tmpfs -o size=5G tmpfs /tmp/qemu_storage
      - name: Installing qemu via apt
        run: sudo apt update -y && sudo apt install qemu qemu-system-misc -y
      - name: Checking whether qemu is available 
        run: qemu-system-riscv64 --version
      - name: Trying to find libguestfs
        run: sudo apt-get install apt-file && sudo apt-file update && apt-file find virt-curtomize
      - name: Checking for virt-builder
        run: virt-builder --version
      - name: Download Fedora "Minimal" vssd image, with extraction followed
        run: wget https://dl.fedoraproject.org/pub/alt/risc-v/repo/virt-builder-images/images/Fedora-Minimal-Rawhide-20200108.n.0-sda.raw.xz && unxz $GITHUB_WORKSPACE/Fedora-Minimal-Rawhide-20200108.n.0-sda.raw.xz && mv Fedora-Minimal-Rawhide-20200108.n.0-sda.raw /tmp/qemu_storage/Fedora-Minimal-Rawhide-20200108.n.0-sda.raw
      - name: Download firmware
        run: wget https://dl.fedoraproject.org/pub/alt/risc-v/repo/virt-builder-images/images/Fedora-Minimal-Rawhide-20200108.n.0-fw_payload-uboot-qemu-virt-smode.elf  
      - name: Modify the disk image, to alter boot sequence
        run: virt-customize -a /tmp/qemu_storage/Fedora-Minimal-Rawhide-20200108.n.0-sda.raw --update
      - name: Firing qemu
        shell: bash
        run: qemu-system-riscv64 -nographic -machine virt -smp 4 -m 2G -kernel $GITHUB_WORKSPACE/Fedora-Minimal-Rawhide-20200108.n.0-fw_payload-uboot-qemu-virt-smode.elf -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-device,rng=rng0 -device virtio-blk-device,drive=hd0 -drive file=/tmp/qemu_storage/Fedora-Minimal-Rawhide-20200108.n.0-sda.raw,format=raw,id=hd0 -device virtio-net-device,netdev=usernet -netdev user,id=usernet,hostfwd=tcp::10000-:22 & ( sleep 30m && ssh root@localhost -p 10000 ) 
